ApplicationPhoto.Web.UI/Controllers/CarteController.cs
using ApplicationPhoto.Web.UI.Data;
using ApplicationPhoto.Web.UI.Models;
using ApplicationPhoto.Web.UI.Services;
using ApplicationPhoto.Web.UI.Services.Interfaces.Generic;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq.Expressions;
using System.Text.Json;

namespace ApplicationPhoto.Web.UI.Controllers
{
    public class CarteController : Controller
    {
       
        
        private readonly PhotoRepository _photoRepository;
        private readonly IRepository<Categorie> _categorieRepository;
        private readonly IRepository<Voyage> _voyageRepository;
        private string userConnect;


        public CarteController(PhotoRepository photoRepository, IRepository<Categorie> categorieRepository, IRepository<Voyage> voyageRepository, IWebHostEnvironment env)
        {
            this.userConnect = "";
            this._photoRepository = photoRepository;
            this._categorieRepository = categorieRepository;
            this._voyageRepository = voyageRepository;
           

        }

        [Authorize]
        public IActionResult Index()
        {

            


            ViewBagCategorie();
            ViewBagVoyage();
           

            return View(_photoRepository.Get(Filter(null,null,null,null)));
        }
        // GET: PictureController/Index/3
        [Authorize]
        [HttpPost]
        public ActionResult Index(int? idCategorie, int? idVoyage, string? depart, string? fin )
        {
            ViewBagCategorie(idCategorie);
            ViewBagVoyage(idVoyage);
            return View(_photoRepository.Get(Filter(idCategorie, idVoyage,depart,fin)));


          
        }
        /// <summary>
        /// Contruit la liste contenant les critére de recherche
        /// </summary>
        /// <param name="idCategorie"></param>
        /// <param name="idVoyage"></param>
        /// <param name="depart"></param>
        /// <param name="fin"></param>
        /// <returns>liste d'Expression lambda contenant le filtre</returns>
        List<Expression<Func<Photo, bool>>> Filter(int? idCategorie, int? idVoyage, string? depart, string? fin)
        {

            List<Expression<Func<Photo, bool>>> listFilter = new List<Expression<Func<Photo, bool>>>();
            listFilter.Add(x => x.Voyage.IdUser == User.Identity.GetUserId());

            if (idVoyage != null)
            {
                listFilter.Add(x => x.VoyageId == idVoyage);
                
            }
            else if (idCategorie != null)
            {
                listFilter.Add(x => x.CategorieId == idCategorie);
              
            }
            else if (depart != null && fin !=null)
            {
               listFilter.Add(x => (x.DatePicture > Convert.ToDateTime(depart) && x.DatePicture < Convert.ToDateTime(fin)));
            }
            else if (depart != null && fin == null)
            {
                listFilter.Add(x => x.DatePicture > Convert.ToDateTime(depart));
            }
            else if (depart == null && fin != null)
            {
                listFilter.Add(x => x.DatePicture < Convert.ToDateTime(fin));
            }

            return listFilter;
        }

      



        private void ViewBagCategorie(int? selectedCategorie = null)
        {

            ViewBag.ListeCategorie = new SelectList(_categorieRepository.GetAll(), "CategorieId", "NameCategorie", selectedCategorie);

           

        }
        private void ViewBagVoyage(int? selectedVoyage = null)
        {
            ViewBag.ListeVoyage = new SelectList(_voyageRepository.Get(FilterUser()), "VoyageId", "NomVoyage", selectedVoyage); 

        }

        List<Expression<Func<Voyage, bool>>> FilterUser()
        {

            List<Expression<Func<Voyage, bool>>> listFilter = new List<Expression<Func<Voyage, bool>>>();
            listFilter.Add(x => x.IdUser == User.Identity.GetUserId());



            return listFilter;
        }

    }
}

ApplicationPhoto.Web.UI/Controllers/PhotoController.cs
using ApplicationPhoto.Web.UI.Models;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using System.Drawing;
using System.IO;
using System.Text;
using System.Web.Helpers;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using ApplicationPhoto.Web.UI.Data;
using ApplicationPhoto.Web.UI.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ApplicationPhoto.Web.UI.Data.Migrations;
using Microsoft.AspNet.Identity;
using Voyage = ApplicationPhoto.Web.UI.Models.Voyage;
using ApplicationPhoto.Web.UI.Utils.ImageTraitement;
using ApplicationPhoto.Web.UI.Services;
using ApplicationPhoto.Web.UI.Models.ViewModel;
using ApplicationPhoto.Web.UI.Services.Interfaces.Generic;
using ApplicationPhoto.Web.UI.Services.Interfaces;

namespace ApplicationPhoto.Web.UI.Controllers
{
    public class PhotoController : Controller
    {
     
        private readonly IWebHostEnvironment _env;
        private readonly IPhotoRepository _photoRepository;
        private readonly IRepository<Categorie> _categorieRepository;
        private readonly IRepository<Voyage> _voyageRepository;
        private string userConnect;


        public PhotoController(IPhotoRepository photoRepository, IRepository<Categorie> categorieRepository, IRepository<Voyage> voyageRepository, IWebHostEnvironment env)
        {
            this.userConnect = "";
            this._photoRepository =photoRepository;
            this._categorieRepository = categorieRepository;
            this._voyageRepository = voyageRepository;
            _env = env;
           
        }


        // GET: PictureController/Index/3
        [Authorize]
        [HttpGet]
        public ActionResult Index(int id, int page = 1)
        {
            userConnect = User.Identity.GetUserId();

            int pageSize = 106; // Nombre d'enregistrements par page
            int totalPages = _photoRepository.GetTotalPages(id,pageSize);
         

            var data = _photoRepository.GetPagedData(page, pageSize, FilterPhotoById(id));

            // Configurez le modèle de vue avec les données et les informations de pagination
            var model = new PhotoPageViewModel
            {
                TotalPages = totalPages,
                CurrentPage = page,
                IdVoyage = id,
                Photos = data
            };


            return View(model);
        }
        [Authorize]
        public ActionResult Index()
        {


            return View();
        }
        #region Détails

        [Authorize]
        // GET: PictureController/Details/5
        public ActionResult Details(int id)
        {
            userConnect = User.Identity.GetUserId();
            if (userConnect == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var photo = _photoRepository.GetByIdInclude((int)id, "Voyage,Categorie");
           // photo.Voyage  = .GetById.VoyageRepository.GetByID(photo.VoyageId, );
//photo.Categorie = unitOfWork.CategorieRepository.GetByID(photo.CategorieId);
            if (photo == null || !VerifUser.UserConnect(photo.Voyage.IdUser, userConnect))
            {
                return NotFound();
            }
            return View(photo);
        }
        #endregion

        #region Create
     
        [Authorize]
        // GET: PictureController/Create
        public ActionResult Create()
        {
            ViewBagPictureCreate("", true, true);
            ViewBagCategorie();
            ViewBagVoyage();
            

            return View ();
        }
        [Authorize]
        // GET: PictureController/CreateMultiple
        public ActionResult CreateMultiple()
        {

            ViewBagVoyage();
            return View();
        }

        [Authorize]
        // POST: PictureController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FilesPhotoViewModel fichier)
        {
                
                int nbrImages = ContientImage(fichier.Files);

                if (nbrImages  > 0)
                {

                foreach (var file in fichier.Files)
                {
                    Photo photo = new Photo
                    {
                        VoyageId = fichier.Photos.VoyageId,
                        CategorieId = fichier.Photos.CategorieId,
                        Description = fichier.Photos.Description

                    };
                        photo.MyImage = file;
                        CreationObjetPhoto(photo);

                        //si il manque une date ou la latitude/longitude on ouvre un panel ( pas dispo pour plusieurs photo)
                        if (!NoExifLatLonDate(photo))
                        {
                            ViewBagPictureCreate("", false, false);
                            return View();
                        }

                        _photoRepository.Add(photo);
                    }


            }
            else
            {
                ViewBagCategorie(fichier.Photos.VoyageId);
                ViewBagVoyage(fichier.Photos.CategorieId);
                return View();
            }
            //refill si on recharge la page si pas de métadonné
           
            return RedirectToAction("Index", new { id = fichier.Photos.VoyageId });

            }


           
        

       
#endregion

#region Edit
[Authorize]
        // GET: PictureController/Edit/5
        public ActionResult Edit(int id)
        {
            userConnect = User.Identity.GetUserId();

            if (userConnect == null)
            {
                return RedirectToAction(nameof(Index));
            }
           
            var photo = _photoRepository.GetByIdInclude((int)id,"Voyage,Categories");
            //photo.Voyage = unitOfWork.VoyageRepository.GetByID(photo.VoyageId);
            if (photo == null || !VerifUser.UserConnect(photo.Voyage.IdUser, userConnect))
            {
                return NotFound();
            }
            ViewBagCategorie(photo.CategorieId);

            return View(photo);
        }
          [Authorize]
        // POST: PictureController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,Photo photo)
        {
            userConnect = User.Identity.GetUserId();
            photo.Voyage = _voyageRepository.GetById(photo.VoyageId);

            if (id != photo.PhotoId || !VerifUser.UserConnect(photo.Voyage.IdUser, userConnect))
            {
                return NotFound();
            }

            if (photo != null)
            {
                try
                {
                    _photoRepository.Update(photo);
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoExists(photo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = photo.VoyageId });
            }
            return View(photo);
        }
        #endregion

        #region Delete
        [Authorize]
        // GET: Picture/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            userConnect = User.Identity.GetUserId();
            if (userConnect == null)
            {
                return RedirectToAction(nameof(Index));
            }
            if (id == null)
            {
                return NotFound();
            }
            
            var photo = _photoRepository.GetByIdInclude((int)id,"Voyage,Categorie");
            //photo.Voyage = _voyageRepository.GetById(photo.VoyageId);
            if (photo == null || !VerifUser.UserConnect(photo.Voyage.IdUser, userConnect))
            {
                return NotFound();
            }

            return View(photo);
        }
        [Authorize]
        // POST: Picture/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            
            var photo = _photoRepository.GetById(id);
            if (photo != null)
            {
                _photoRepository.Delete(photo);
                

                ImageDeleter.DeleteImage(Path.Combine(_env.WebRootPath, photo.ImageUrl));
            }

        
            return RedirectToAction("Index", new { id = photo.VoyageId });
        }

        #endregion

        #region Methode de filtre

        List<Expression<Func<Photo, bool>>> FilterPhotoById(int id)
        {

            List<Expression<Func<Photo, bool>>> expressions;
            expressions = new List<Expression<Func<Photo, bool>> >();
            expressions.Add(x => x.VoyageId == id);
            expressions.Add(x => x.Voyage.IdUser == userConnect);
             return expressions;
          

        }
        List<Expression<Func<Voyage, bool>>> FilterUser()
        {

            List<Expression<Func<Voyage, bool>>> listFilter = new List<Expression<Func<Voyage, bool>>>();
            listFilter.Add(x => x.IdUser == User.Identity.GetUserId());



            return listFilter;
        }
        #endregion

        #region Methodes privées
        private int ContientImage(List<IFormFile> files)
        {
            return files.Count();
        }

        private Photo CreationObjetPhoto(Photo photo)
        {

            ImageO monImage = new ImageO();
            ImageSaver imageSaver = new ImageSaver(monImage, photo, _env);
            Image image = imageSaver.SaveImage();

ApplicationPhoto.Web.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Place my pictures</title>
    <!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/logopmp.png"/>
   
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApplicationPhoto.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       
        <nav class="navbar  navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3 backgroundNav">
            <div class="container-fluid">
                <a class="navbar-brand mt-2 mt-lg-0" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo_square.png"
                         height="35"
                         alt="Logo"
                         loading="lazy" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
 @if (SignInManager.IsSignedIn(User))
{
                  <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Carte" asp-action="Index">Carte</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Voyage" asp-action="Index">Voyage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Photo" asp-action="Create">Ajouter Photos</a>
                        </li>
}                       

                       
                      
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
   
    <div class="container containerMain">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footerRedefine text-muted">
        <div class="container">
            &copy; 2022 - PlaceMyPictures - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ApplicationPhoto.Web.UI/Views/Shared/_Layout_carte.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Place my pictures</title>
    <!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApplicationPhoto.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
   
        
            @RenderBody()
   
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>